export enum StorageKeys {
  ENV = 'ENV',
  USER_LANGUAGE = 'USER_LANGUAGE',
  APP_THEME = 'APP_THEME',
  LOGIN = 'LOGIN',
  LOGIN_USER = 'LOGIN_USER',
  AUTH_TOKEN = 'AUTH_TOKEN',
  DEVICE_TOKEN = 'DEVICE_TOKEN',
  LANGUAGE = 'LANGUAGE',
}
